name: tailwindcss_colors
description: "Tailwind CSS color palette for Flutter apps."
version: 4.1.14+2
repository: https://github.com/fondoger/tailwindcss-utilities/tree/main/dart_package
issue_tracker: https://github.com/fondoger/tailwindcss-utilities/issues

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
